### ISSUE TITLE
Remove access token from User

### ISSUE THREAD

**Issue by armpogart** [yiisoft/user#3]
- [x] Remove `IdentityRepositoryInterface::findIdentityByToken` (yiisoft/auth#37)
- [x] Add separate `IdentityRepositoryInterface` with the token (yiisoft/auth#37)
- [x] Refactor `Yiisoft\Auth\Method\HttpBasic`, `Yiisoft\Auth\Method\HttpHeader`, `Yiisoft\Auth\Method\QueryParam` to depend on the new interface. (yiisoft/auth#37)
- [x] Remove `User::loginByAccessToken` functionality altogether. We don't need it there for anything. I don't see any code that specifically uses it. And I don't see any reason we have to provide such API when `Yiisoft\Auth\Middleware\Auth` can do that with its' respective `AuthInterface` implementations (mentioned above). (#20)
- [x] Remove access token functionality from yii-demo (`App\Repository\UserRepository`) (yiisoft/yii-demo#224)

**Comment by armpogart** [comment]
The issue description is updated with corresponding PR links.
Concerning the last point I'm not sure whether we should remove that method from `UserRepository` or just implement the new interface.

**Comment by roxblnfk** [comment]
> Concerning the last point I'm not sure whether we should remove that method from `UserRepository` or just implement the new interface.

Just remove. Someone has already removed the `token` field from the `User` class and the `findIdentityByToken` method is not used.

**Comment by samdark** [comment]
Merged all the PRs linked. What's left, @armpogart?

**Comment by armpogart** [comment]
@samdark yiisoft/auth#38 and yiisoft/yii-demo#224
If I haven't forgotten anything, after merging those 2 PRs the issue can be closed.

**Comment by samdark** [comment]
All merged. Thanks for hadling it.
